### PR TITLE
Fix - Removed array destructing from plugins find

### PR DESCRIPTION
**Pull request by luanraithz**
I'm getting this error within my project
image

That little change seems to have that fixed.
I'm not able to run the tests even before my change, they just seem to run forever.

### CODE REVIEW

**Comment by TrevorBurnham** [comment]
Hmm. I think we actually need to accommodate both: Babel's `plugins` is an array where each item can be either a plugin or an array of the form `[plugin, options]` ([example](https://github.com/babel/babel/blob/97f0b7c4a0589cf3cf1dae62fb09d1b7f1253829/packages/babel-standalone/src/preset-es2015.js#L19-L54)). Can you update this PR accordingly?

**Comment by luanraithz** [comment]
Sure!

**Comment by luanraithz** [comment]
Any other change required?

**Comment by TrevorBurnham** [comment]
Published as v0.4.1. Thanks!

**Pull request merged**
